define_directive {v:work.cordic_top} {.noprune} {1}
define_directive {v:work.cordic_top} {.distcompnoprune} {1}
define_directive {v:work.fifo} {.noprune} {1}
define_directive {v:work.fifo} {.distcompnoprune} {1}
define_directive {v:work.cordic_module} {.noprune} {1}
define_directive {v:work.cordic_module} {.distcompnoprune} {1}
define_directive {v:work.cordic_stage} {.noprune} {1}
define_directive {v:work.cordic_stage} {.distcompnoprune} {1}
define_directive {v:work.cordic_top} {.distcompmodetop} {1}
