set paths_array(status_msg,2) {}
set paths_array(s_line,2) {0}
set paths_array(end_clock,2) {Top|clock:falling}
set paths_array(margin_msg,1) {}
set paths_array(e_line,1) {0}
set paths_array(margin_msg,2) {}
set paths_array(e_line,2) {0}
set paths_array(req_time,1) {1000.0}
set paths_array(slack,1) {994.401}
set paths_array(slack,2) {998.335}
set paths_array(req_time,2) {1000.0}
set paths_array(TS,1) {}
set paths_array(start_point,1) {ram_x/brams\[0\]/mem}
set paths_array(TS,2) {}
set paths_array(start_point,2) {matmul_instance}
set paths_array(end_clk_dly,1) {0.000}
set paths_array(end_clk_dly,2) {0.000}
set paths_array(start_clock,1) {Top|clock:falling}
set paths_array(start_clock,2) {System:rising}
set paths_array(skew,1) {0.0}
set paths_array(skew,2) {0.0}
set paths_array(sig) {/home/sfs6562/CE495-Digital-design-and-Verification/HW2/proj_1.prj|rev_1 {} /home/sfs6562/CE495-Digital-design-and-Verification/HW2/rev_1/sdc_verif_slack.itd correlate 1 slack 1 {} {} {} {} {} {} 0 1 0 1 1}
set paths_array(margin,1) {0}
set paths_array(pro_slack,1) {0}
set paths_array(margin,2) {0}
set paths_array(pro_slack,2) {0}
set paths_array(start_type,1) {reg}
set paths_array(start_clk_dly,1) {0.000}
set paths_array(start_clk_dly,2) {0.000}
set paths_array(start_type,2) {reg}
set paths_array(index,1) {1}
set paths_array(passed,1) {0}
set paths_array(end_point,1) {matmul_instance}
set paths_array(end_type,1) {reg}
set paths_array(data_delay,1) {0}
set paths_array(index,2) {2}
set paths_array(passed,2) {0}
set paths_array(data_delay,2) {0}
set paths_array(end_type,2) {reg}
set paths_array(end_point,2) {ram_x/brams\[0\]/mem.eq_reg[0]}
set paths_array(status_msg,1) {}
set paths_array(s_line,1) {0}
set paths_array(end_clock,1) {System:rising}
set synth_array(end_clock,2) {}
set synth_array(req_time,1) {}
set synth_array(slack,1) {}
set synth_array(slack,2) {}
set synth_array(req_time,2) {}
set synth_array(start_point,1) {}
set synth_array(end_clk_dly,1) {}
set synth_array(start_point,2) {}
set synth_array(end_clk_dly,2) {}
set synth_array(start_clock,1) {}
set synth_array(start_clock,2) {}
set synth_array(skew,1) {}
set synth_array(skew,2) {}
set synth_array(start_type,1) {}
set synth_array(start_clk_dly,1) {}
set synth_array(start_clk_dly,2) {}
set synth_array(start_type,2) {}
set synth_array(end_point,1) {}
set synth_array(end_type,1) {}
set synth_array(end_type,2) {}
set synth_array(end_point,2) {}
set synth_array(end_clock,1) {}
set sort_list {1 NA 2 NA}
set clock_list {}
set foo {ctd_ta_point,matmul_instance}
set ta_array($foo) {matmul_instance}
set foo {ctd_ta_point,ram_x/brams\[0\]/mem}
set ta_array($foo) {ram_x.brams\[0\].mem}
set foo {ctd_ta_point,ram_x/brams\[0\]/mem.eq_reg[0]}
set ta_array($foo) {ram_x.brams\[0\].mem.eq_reg[0]}
puts ""
